Revert "[entry] added feature - getting intersection region of viewport objects"
This reverts commit 40b5267dacce2f02b048df7e046ad7b5761e44f0.

Doesn't build! Should be submitted upstream first!

  CC     libelementary_la-elm_entry.lo
elm_entry.c: In function '_move':
elm_entry.c:1076:25: warning: unused variable 'ret_rect'
elm_entry.c: In function '_matchlist_show':
elm_entry.c:1764:17: warning: implicit declaration of function 'strcasestr'
elm_entry.c:1764:28: warning: assignment makes pointer from integer without a cast
elm_entry.c: In function '_matchlist_list_clicked':
elm_entry.c:1840:14: warning: passing argument 1 of 'free' discards qualifiers from pointer target type
/usr/include/stdlib.h:488:13: note: expected 'void *' but argument is of type 'const char *'
elm_entry.c: In function '_elm_win_region_get_job':
elm_entry.c:2050:9: error: incompatible type for argument 3 of 'edje_object_part_text_viewport_region_set'
/usr/include/edje-1/Edje.h:2970:46: note: expected 'Evas_Coord_Rectangle' but argument is of type 'Evas_Coord'
elm_entry.c:2050:9: error: too many arguments to function 'edje_object_part_text_viewport_region_set'
/usr/include/edje-1/Edje.h:2970:46: note: declared here
elm_entry.c:2052:9: error: incompatible type for argument 3 of 'edje_object_part_text_layout_region_set'
/usr/include/edje-1/Edje.h:2980:46: note: expected 'Evas_Coord_Rectangle' but argument is of type 'Evas_Coord'
elm_entry.c:2052:9: error: too many arguments to function 'edje_object_part_text_layout_region_set'
/usr/include/edje-1/Edje.h:2980:46: note: declared here
elm_entry.c: In function '_elm_entry_text_get':
elm_entry.c:2884:14: warning: passing argument 1 of 'free' discards qualifiers from pointer target type
/usr/include/stdlib.h:488:13: note: expected 'void *' but argument is of type 'const char *'
elm_entry.c: In function 'elm_entry_add':
elm_entry.c:2934:4: warning: implicit declaration of function 'elm_smart_scroller_propagate_events_set'
elm_entry.c:2973:36: warning: passing argument 4 of 'edje_object_signal_callback_add' from incompatible pointer type
/usr/include/edje-1/Edje.h:1930:46: note: expected 'Edje_Signal_Cb' but argument is of type 'Eina_Bool (*)(void *)'
elm_entry.c:3013:9: warning: implicit declaration of function 'edje_object_part_text_copy_paste_disabled_set'
elm_entry.c:3014:9: error: incompatible type for argument 3 of 'edje_object_part_text_viewport_region_set'
/usr/include/edje-1/Edje.h:2970:46: note: expected 'Evas_Coord_Rectangle' but argument is of type 'int'
elm_entry.c:3014:9: error: too many arguments to function 'edje_object_part_text_viewport_region_set'
/usr/include/edje-1/Edje.h:2970:46: note: declared here
elm_entry.c:3015:9: error: incompatible type for argument 3 of 'edje_object_part_text_layout_region_set'
/usr/include/edje-1/Edje.h:2980:46: note: expected 'Evas_Coord_Rectangle' but argument is of type 'int'
elm_entry.c:3015:9: error: too many arguments to function 'edje_object_part_text_layout_region_set'
/usr/include/edje-1/Edje.h:2980:46: note: declared here
make[4]: *** [libelementary_la-elm_entry.lo] Error 1